package base;

import java.util.List;

/**
 * An ICPConsole handles the user input/output operations for the application 
 */
public interface ICPConsole {
    /**
     * Specify the controller that will receive the user events generated by this console
     * @param controller
     */
    void setController(ICPController controller);

    /**
     * Prints a list of options and reads user selection
     * @param options 
     */
    void showOptions(List<String> options);

    /**
     * Reads the data needed to create or update a Person
     * @param update
     */
    void readPerson(boolean update);

    /**
     * Prints a message
     * @param message
     */
    void showMessage(String message);

    /**
     * Prints a message in interactive mode.
     * @param message
     */
    void showInteractiveInfo(String message);

    /**
     * Retrives a string
     * @param message a message requesting a string input
     */
    void getString(String message);
}